name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite: ^2.3.2
  path: ^1.8.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/
